// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Api.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Api.Domain.Entities.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("CodeIBGE")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UfId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeIBGE");

                    b.HasIndex("UfId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Api.Domain.Entities.CodeZipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Number")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ZipCode");

                    b.ToTable("ZipCode");
                });

            modelBuilder.Entity("Api.Domain.Entities.UfEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("UfName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("Uf");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ffbd18-cdb9-45cc-97b0-51e97700bf71"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(6970),
                            Sigla = "AC",
                            UfName = "Acre"
                        },
                        new
                        {
                            Id = new Guid("7cc33300-586e-4be8-9a4d-bd9f01ee9ad8"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9390),
                            Sigla = "AL",
                            UfName = "Alagoas"
                        },
                        new
                        {
                            Id = new Guid("cb9e6888-2094-45ee-bc44-37ced33c693a"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9390),
                            Sigla = "AM",
                            UfName = "Amazonas"
                        },
                        new
                        {
                            Id = new Guid("409b9043-88a4-4e86-9cca-ca1fb0d0d35b"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9400),
                            Sigla = "AP",
                            UfName = "Amapá"
                        },
                        new
                        {
                            Id = new Guid("5abca453-d035-4766-a81b-9f73d683a54b"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9400),
                            Sigla = "BA",
                            UfName = "Bahia"
                        },
                        new
                        {
                            Id = new Guid("5ff1b59e-11e7-414d-827e-609dc5f7e333"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9400),
                            Sigla = "CE",
                            UfName = "Ceará"
                        },
                        new
                        {
                            Id = new Guid("bd08208b-bfca-47a4-9cd0-37e4e1fa5006"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9410),
                            Sigla = "DF",
                            UfName = "Distrito Federal"
                        },
                        new
                        {
                            Id = new Guid("c623f804-37d8-4a19-92c1-67fd162862e6"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9410),
                            Sigla = "ES",
                            UfName = "Espírito Santo"
                        },
                        new
                        {
                            Id = new Guid("837a64d3-c649-4172-a4e0-2b20d3c85224"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9410),
                            Sigla = "GO",
                            UfName = "Goiás"
                        },
                        new
                        {
                            Id = new Guid("57a9e9f7-9aea-40fe-a783-65d4feb59fa8"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9420),
                            Sigla = "MA",
                            UfName = "Maranhão"
                        },
                        new
                        {
                            Id = new Guid("27f7a92b-1979-4e1c-be9d-cd3bb73552a8"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9420),
                            Sigla = "MG",
                            UfName = "Minas Gerais"
                        },
                        new
                        {
                            Id = new Guid("3739969c-fd8a-4411-9faa-3f718ca85e70"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9420),
                            Sigla = "MS",
                            UfName = "Mato Grosso do Sul"
                        },
                        new
                        {
                            Id = new Guid("29eec4d3-b061-427d-894f-7f0fecc7f65f"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9420),
                            Sigla = "MT",
                            UfName = "Mato Grosso"
                        },
                        new
                        {
                            Id = new Guid("8411e9bc-d3b2-4a9b-9d15-78633d64fc7c"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9430),
                            Sigla = "PA",
                            UfName = "Pará"
                        },
                        new
                        {
                            Id = new Guid("1109ab04-a3a5-476e-bdce-6c3e2c2badee"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9450),
                            Sigla = "PB",
                            UfName = "Paraíba"
                        },
                        new
                        {
                            Id = new Guid("ad5969bd-82dc-4e23-ace2-d8495935dd2e"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9450),
                            Sigla = "PE",
                            UfName = "Pernambuco"
                        },
                        new
                        {
                            Id = new Guid("f85a6cd0-2237-46b1-a103-d3494ab27774"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9450),
                            Sigla = "PI",
                            UfName = "Piauí"
                        },
                        new
                        {
                            Id = new Guid("1dd25850-6270-48f8-8b77-2f0f079480ab"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9460),
                            Sigla = "PR",
                            UfName = "Paraná"
                        },
                        new
                        {
                            Id = new Guid("43a0f783-a042-4c46-8688-5dd4489d2ec7"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9460),
                            Sigla = "RJ",
                            UfName = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("542668d1-50ba-4fca-bbc3-4b27af108ea3"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9460),
                            Sigla = "RN",
                            UfName = "Rio Grande do Norte"
                        },
                        new
                        {
                            Id = new Guid("924e7250-7d39-4e8b-86bf-a8578cbf4002"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9460),
                            Sigla = "RO",
                            UfName = "Rondônia"
                        },
                        new
                        {
                            Id = new Guid("9fd3c97a-dc68-4af5-bc65-694cca0f2869"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9470),
                            Sigla = "RR",
                            UfName = "Roraima"
                        },
                        new
                        {
                            Id = new Guid("88970a32-3a2a-4a95-8a18-2087b65f59d1"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9470),
                            Sigla = "RS",
                            UfName = "Rio Grande do Sul"
                        },
                        new
                        {
                            Id = new Guid("b81f95e0-f226-4afd-9763-290001637ed4"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9470),
                            Sigla = "SC",
                            UfName = "Santa Catarina"
                        },
                        new
                        {
                            Id = new Guid("fe8ca516-034f-4249-bc5a-31c85ef220ea"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9480),
                            Sigla = "SE",
                            UfName = "Sergipe"
                        },
                        new
                        {
                            Id = new Guid("e7e416de-477c-4fa3-a541-b5af5f35ccf6"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9480),
                            Sigla = "SP",
                            UfName = "São Paulo"
                        },
                        new
                        {
                            Id = new Guid("971dcb34-86ea-4f92-989d-064f749e23c9"),
                            CreatedAt = new DateTime(2021, 8, 11, 13, 29, 1, 169, DateTimeKind.Utc).AddTicks(9480),
                            Sigla = "TO",
                            UfName = "Tocantins"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2bcb8b73-3d96-48f3-8fd2-8ec12bb72e6f"),
                            CreatedAt = new DateTime(2021, 8, 11, 10, 29, 1, 171, DateTimeKind.Local).AddTicks(5090),
                            Email = "administrador@geral.com",
                            Name = "administrador",
                            UpdateAt = new DateTime(2021, 8, 11, 10, 29, 1, 191, DateTimeKind.Local).AddTicks(1510)
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.CityEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.UfEntity", "Uf")
                        .WithMany("Cities")
                        .HasForeignKey("UfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("Api.Domain.Entities.CodeZipEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.CityEntity", "City")
                        .WithMany("CodeZip")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Api.Domain.Entities.CityEntity", b =>
                {
                    b.Navigation("CodeZip");
                });

            modelBuilder.Entity("Api.Domain.Entities.UfEntity", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
